**1. Import the numpy package under the name np** 

In [2]:
# Import the numpy package under the name "np"
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
# Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\include']
None


**3. Create a null vector of size 10**

In [4]:
# Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array**

In [5]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


**5. How to get the documentation of the numpy add function**

In [6]:
# How to get the documentation of the numpy add function from the command line
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

**6. Create a null vector of size 10 but the fifth value which is 1**

In [7]:
# Create a null vector of size 10 but the fifth value which is 1
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49**

In [8]:
# Create a vector with values ranging from 10 to 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8. Reverse a vector (first element becomes last)**

In [9]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


**11. Create a 3x3 identity matrix**

In [12]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**12. Create a 3x3x3 array with random values**

In [13]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.58553851 0.25622943 0.87809505]
  [0.66215189 0.27772288 0.79925981]
  [0.55356827 0.48793659 0.10235013]]

 [[0.99347267 0.41959681 0.83294163]
  [0.73409997 0.55172629 0.25937689]
  [0.8623987  0.71427267 0.78618499]]

 [[0.74352982 0.77402168 0.31424323]
  [0.16799844 0.1649076  0.0268391 ]
  [0.81861003 0.99030411 0.91366485]]]


**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [14]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0031292082377594177 0.9888298912852115


**14. Create a random vector of size 30 and find the mean value**

In [15]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.52344989034489


**15. Create a 2d array with 1 on the border and 0 inside**

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**16. Add a border (filled with 0's) around an existing array?**

In [17]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**17. What is the result of the following expression?**

In [18]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [20]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**19. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [21]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [22]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


**21. Create a checkerboard 8x8 matrix using the tile function**

In [23]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**22. Normalize a 5x5 random matrix**

In [24]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.46296717  1.11579895 -1.43408062 -0.98797799 -0.71665692]
 [ 1.05722631 -0.90647159  0.13626617  1.60758244 -1.20994501]
 [-1.17953791  0.40361359  0.39162223 -0.37389274  0.78016578]
 [ 0.5877247   0.53566902  0.86662673  0.32188825 -1.3108554 ]
 [-0.74026602  2.00823615 -1.42443019 -0.33263734  1.26729859]]


**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)**

In [25]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [26]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**25. Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [27]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
